/*
 * Id service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@breffi.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.breffi.storyid.generated_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets StoryAppType
 */
@JsonAdapter(StoryAppType.Adapter.class)
public enum StoryAppType {
  
  NUMBER_0(0),
  
  NUMBER_1(1),
  
  NUMBER_2(2),
  
  NUMBER_3(3),
  
  NUMBER_4(4);

  private Integer value;

  StoryAppType(Integer value) {
    this.value = value;
  }

  public Integer getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static StoryAppType fromValue(Integer value) {
    for (StoryAppType b : StoryAppType.values()) {
      if (b.value.equals(value)) {
        return b;
      }
    }
    throw new IllegalArgumentException("Unexpected value '" + value + "'");
  }

  public static class Adapter extends TypeAdapter<StoryAppType> {
    @Override
    public void write(final JsonWriter jsonWriter, final StoryAppType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public StoryAppType read(final JsonReader jsonReader) throws IOException {
      Integer value = jsonReader.nextInt();
      return StoryAppType.fromValue(value);
    }
  }
}

