/*
 * Id service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@breffi.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.breffi.storyid.generated_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * StoryITN
 */

public class StoryITN {
  public static final String SERIALIZED_NAME_PROFILE_ID = "profileId";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  private String profileId;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private DateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  private Boolean verified;

  public static final String SERIALIZED_NAME_VERIFIED_AT = "verifiedAt";
  @SerializedName(SERIALIZED_NAME_VERIFIED_AT)
  private DateTime verifiedAt;

  public static final String SERIALIZED_NAME_VERIFIED_BY = "verifiedBy";
  @SerializedName(SERIALIZED_NAME_VERIFIED_BY)
  private String verifiedBy;

  public static final String SERIALIZED_NAME_SIZE = "size";
  @SerializedName(SERIALIZED_NAME_SIZE)
  private Long size;

  public static final String SERIALIZED_NAME_MIME_TYPE = "mimeType";
  @SerializedName(SERIALIZED_NAME_MIME_TYPE)
  private String mimeType;

  public static final String SERIALIZED_NAME_ITN = "itn";
  @SerializedName(SERIALIZED_NAME_ITN)
  private String itn;


  public StoryITN profileId(String profileId) {
    
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProfileId() {
    return profileId;
  }


  public void setProfileId(String profileId) {
    this.profileId = profileId;
  }


  public StoryITN modifiedAt(DateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(DateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public StoryITN modifiedBy(String modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public StoryITN verified(Boolean verified) {
    
    this.verified = verified;
    return this;
  }

   /**
   * Get verified
   * @return verified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getVerified() {
    return verified;
  }


  public void setVerified(Boolean verified) {
    this.verified = verified;
  }


  public StoryITN verifiedAt(DateTime verifiedAt) {
    
    this.verifiedAt = verifiedAt;
    return this;
  }

   /**
   * Get verifiedAt
   * @return verifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getVerifiedAt() {
    return verifiedAt;
  }


  public void setVerifiedAt(DateTime verifiedAt) {
    this.verifiedAt = verifiedAt;
  }


  public StoryITN verifiedBy(String verifiedBy) {
    
    this.verifiedBy = verifiedBy;
    return this;
  }

   /**
   * Get verifiedBy
   * @return verifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVerifiedBy() {
    return verifiedBy;
  }


  public void setVerifiedBy(String verifiedBy) {
    this.verifiedBy = verifiedBy;
  }


  public StoryITN size(Long size) {
    
    this.size = size;
    return this;
  }

   /**
   * Get size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getSize() {
    return size;
  }


  public void setSize(Long size) {
    this.size = size;
  }


  public StoryITN mimeType(String mimeType) {
    
    this.mimeType = mimeType;
    return this;
  }

   /**
   * Get mimeType
   * @return mimeType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getMimeType() {
    return mimeType;
  }


  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }


  public StoryITN itn(String itn) {
    
    this.itn = itn;
    return this;
  }

   /**
   * Get itn
   * @return itn
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getItn() {
    return itn;
  }


  public void setItn(String itn) {
    this.itn = itn;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoryITN storyITN = (StoryITN) o;
    return Objects.equals(this.profileId, storyITN.profileId) &&
        Objects.equals(this.modifiedAt, storyITN.modifiedAt) &&
        Objects.equals(this.modifiedBy, storyITN.modifiedBy) &&
        Objects.equals(this.verified, storyITN.verified) &&
        Objects.equals(this.verifiedAt, storyITN.verifiedAt) &&
        Objects.equals(this.verifiedBy, storyITN.verifiedBy) &&
        Objects.equals(this.size, storyITN.size) &&
        Objects.equals(this.mimeType, storyITN.mimeType) &&
        Objects.equals(this.itn, storyITN.itn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileId, modifiedAt, modifiedBy, verified, verifiedAt, verifiedBy, size, mimeType, itn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoryITN {\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    verifiedAt: ").append(toIndentedString(verifiedAt)).append("\n");
    sb.append("    verifiedBy: ").append(toIndentedString(verifiedBy)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    itn: ").append(toIndentedString(itn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

