/*
 * Id service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@breffi.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.breffi.storyid.generated_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * StoryDemographics
 */

public class StoryDemographics {
  public static final String SERIALIZED_NAME_PROFILE_ID = "profileId";
  @SerializedName(SERIALIZED_NAME_PROFILE_ID)
  private String profileId;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private DateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_VERIFIED = "verified";
  @SerializedName(SERIALIZED_NAME_VERIFIED)
  private Boolean verified;

  public static final String SERIALIZED_NAME_VERIFIED_AT = "verifiedAt";
  @SerializedName(SERIALIZED_NAME_VERIFIED_AT)
  private DateTime verifiedAt;

  public static final String SERIALIZED_NAME_VERIFIED_BY = "verifiedBy";
  @SerializedName(SERIALIZED_NAME_VERIFIED_BY)
  private String verifiedBy;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SURNAME = "surname";
  @SerializedName(SERIALIZED_NAME_SURNAME)
  private String surname;

  public static final String SERIALIZED_NAME_PATRONYMIC = "patronymic";
  @SerializedName(SERIALIZED_NAME_PATRONYMIC)
  private String patronymic;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private Boolean gender;

  public static final String SERIALIZED_NAME_BIRTHDAY = "birthday";
  @SerializedName(SERIALIZED_NAME_BIRTHDAY)
  private DateTime birthday;


  public StoryDemographics profileId(String profileId) {
    
    this.profileId = profileId;
    return this;
  }

   /**
   * Get profileId
   * @return profileId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProfileId() {
    return profileId;
  }


  public void setProfileId(String profileId) {
    this.profileId = profileId;
  }


  public StoryDemographics modifiedAt(DateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(DateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public StoryDemographics modifiedBy(String modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public StoryDemographics verified(Boolean verified) {
    
    this.verified = verified;
    return this;
  }

   /**
   * Get verified
   * @return verified
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getVerified() {
    return verified;
  }


  public void setVerified(Boolean verified) {
    this.verified = verified;
  }


  public StoryDemographics verifiedAt(DateTime verifiedAt) {
    
    this.verifiedAt = verifiedAt;
    return this;
  }

   /**
   * Get verifiedAt
   * @return verifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getVerifiedAt() {
    return verifiedAt;
  }


  public void setVerifiedAt(DateTime verifiedAt) {
    this.verifiedAt = verifiedAt;
  }


  public StoryDemographics verifiedBy(String verifiedBy) {
    
    this.verifiedBy = verifiedBy;
    return this;
  }

   /**
   * Get verifiedBy
   * @return verifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVerifiedBy() {
    return verifiedBy;
  }


  public void setVerifiedBy(String verifiedBy) {
    this.verifiedBy = verifiedBy;
  }


  public StoryDemographics name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public StoryDemographics surname(String surname) {
    
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSurname() {
    return surname;
  }


  public void setSurname(String surname) {
    this.surname = surname;
  }


  public StoryDemographics patronymic(String patronymic) {
    
    this.patronymic = patronymic;
    return this;
  }

   /**
   * Get patronymic
   * @return patronymic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPatronymic() {
    return patronymic;
  }


  public void setPatronymic(String patronymic) {
    this.patronymic = patronymic;
  }


  public StoryDemographics gender(Boolean gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getGender() {
    return gender;
  }


  public void setGender(Boolean gender) {
    this.gender = gender;
  }


  public StoryDemographics birthday(DateTime birthday) {
    
    this.birthday = birthday;
    return this;
  }

   /**
   * Get birthday
   * @return birthday
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getBirthday() {
    return birthday;
  }


  public void setBirthday(DateTime birthday) {
    this.birthday = birthday;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoryDemographics storyDemographics = (StoryDemographics) o;
    return Objects.equals(this.profileId, storyDemographics.profileId) &&
        Objects.equals(this.modifiedAt, storyDemographics.modifiedAt) &&
        Objects.equals(this.modifiedBy, storyDemographics.modifiedBy) &&
        Objects.equals(this.verified, storyDemographics.verified) &&
        Objects.equals(this.verifiedAt, storyDemographics.verifiedAt) &&
        Objects.equals(this.verifiedBy, storyDemographics.verifiedBy) &&
        Objects.equals(this.name, storyDemographics.name) &&
        Objects.equals(this.surname, storyDemographics.surname) &&
        Objects.equals(this.patronymic, storyDemographics.patronymic) &&
        Objects.equals(this.gender, storyDemographics.gender) &&
        Objects.equals(this.birthday, storyDemographics.birthday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(profileId, modifiedAt, modifiedBy, verified, verifiedAt, verifiedBy, name, surname, patronymic, gender, birthday);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoryDemographics {\n");
    sb.append("    profileId: ").append(toIndentedString(profileId)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    verified: ").append(toIndentedString(verified)).append("\n");
    sb.append("    verifiedAt: ").append(toIndentedString(verifiedAt)).append("\n");
    sb.append("    verifiedBy: ").append(toIndentedString(verifiedBy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    patronymic: ").append(toIndentedString(patronymic)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

