/*
 * Id service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@breffi.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.breffi.storyid.generated_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * StoryBankAccountDTO
 */

public class StoryBankAccountDTO {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_SETTLEMENT_ACCOUNT = "settlementAccount";
  @SerializedName(SERIALIZED_NAME_SETTLEMENT_ACCOUNT)
  private String settlementAccount;

  public static final String SERIALIZED_NAME_BANK = "bank";
  @SerializedName(SERIALIZED_NAME_BANK)
  private String bank;

  public static final String SERIALIZED_NAME_BIC = "bic";
  @SerializedName(SERIALIZED_NAME_BIC)
  private String bic;

  public static final String SERIALIZED_NAME_CORRESPONDENT_ACCOUNT = "correspondentAccount";
  @SerializedName(SERIALIZED_NAME_CORRESPONDENT_ACCOUNT)
  private String correspondentAccount;


  public StoryBankAccountDTO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public StoryBankAccountDTO description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public StoryBankAccountDTO settlementAccount(String settlementAccount) {
    
    this.settlementAccount = settlementAccount;
    return this;
  }

   /**
   * Get settlementAccount
   * @return settlementAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSettlementAccount() {
    return settlementAccount;
  }


  public void setSettlementAccount(String settlementAccount) {
    this.settlementAccount = settlementAccount;
  }


  public StoryBankAccountDTO bank(String bank) {
    
    this.bank = bank;
    return this;
  }

   /**
   * Get bank
   * @return bank
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBank() {
    return bank;
  }


  public void setBank(String bank) {
    this.bank = bank;
  }


  public StoryBankAccountDTO bic(String bic) {
    
    this.bic = bic;
    return this;
  }

   /**
   * Get bic
   * @return bic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBic() {
    return bic;
  }


  public void setBic(String bic) {
    this.bic = bic;
  }


  public StoryBankAccountDTO correspondentAccount(String correspondentAccount) {
    
    this.correspondentAccount = correspondentAccount;
    return this;
  }

   /**
   * Get correspondentAccount
   * @return correspondentAccount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCorrespondentAccount() {
    return correspondentAccount;
  }


  public void setCorrespondentAccount(String correspondentAccount) {
    this.correspondentAccount = correspondentAccount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoryBankAccountDTO storyBankAccountDTO = (StoryBankAccountDTO) o;
    return Objects.equals(this.name, storyBankAccountDTO.name) &&
        Objects.equals(this.description, storyBankAccountDTO.description) &&
        Objects.equals(this.settlementAccount, storyBankAccountDTO.settlementAccount) &&
        Objects.equals(this.bank, storyBankAccountDTO.bank) &&
        Objects.equals(this.bic, storyBankAccountDTO.bic) &&
        Objects.equals(this.correspondentAccount, storyBankAccountDTO.correspondentAccount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, description, settlementAccount, bank, bic, correspondentAccount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoryBankAccountDTO {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    settlementAccount: ").append(toIndentedString(settlementAccount)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    correspondentAccount: ").append(toIndentedString(correspondentAccount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

