/*
 * Id service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@breffi.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.breffi.storyid.generated_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * StoryAppUser
 */

public class StoryAppUser {
  public static final String SERIALIZED_NAME_APP_ID = "appId";
  @SerializedName(SERIALIZED_NAME_APP_ID)
  private String appId;

  public static final String SERIALIZED_NAME_USER_ID = "userId";
  @SerializedName(SERIALIZED_NAME_USER_ID)
  private String userId;

  public static final String SERIALIZED_NAME_BLOCK_DESCRIPTION = "blockDescription";
  @SerializedName(SERIALIZED_NAME_BLOCK_DESCRIPTION)
  private String blockDescription;

  public static final String SERIALIZED_NAME_BLOCKED = "blocked";
  @SerializedName(SERIALIZED_NAME_BLOCKED)
  private Boolean blocked;

  public static final String SERIALIZED_NAME_BLOCKED_UNTIL = "blockedUntil";
  @SerializedName(SERIALIZED_NAME_BLOCKED_UNTIL)
  private DateTime blockedUntil;

  public static final String SERIALIZED_NAME_BLOCKED_AT = "blockedAt";
  @SerializedName(SERIALIZED_NAME_BLOCKED_AT)
  private DateTime blockedAt;

  public static final String SERIALIZED_NAME_BLOCKED_BY = "blockedBy";
  @SerializedName(SERIALIZED_NAME_BLOCKED_BY)
  private String blockedBy;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private DateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private String createdBy;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private DateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private String modifiedBy;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;


  public StoryAppUser appId(String appId) {
    
    this.appId = appId;
    return this;
  }

   /**
   * Get appId
   * @return appId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getAppId() {
    return appId;
  }


  public void setAppId(String appId) {
    this.appId = appId;
  }


  public StoryAppUser userId(String userId) {
    
    this.userId = userId;
    return this;
  }

   /**
   * Get userId
   * @return userId
  **/
  @ApiModelProperty(required = true, value = "")

  public String getUserId() {
    return userId;
  }


  public void setUserId(String userId) {
    this.userId = userId;
  }


  public StoryAppUser blockDescription(String blockDescription) {
    
    this.blockDescription = blockDescription;
    return this;
  }

   /**
   * Get blockDescription
   * @return blockDescription
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBlockDescription() {
    return blockDescription;
  }


  public void setBlockDescription(String blockDescription) {
    this.blockDescription = blockDescription;
  }


  public StoryAppUser blocked(Boolean blocked) {
    
    this.blocked = blocked;
    return this;
  }

   /**
   * Get blocked
   * @return blocked
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getBlocked() {
    return blocked;
  }


  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }


  public StoryAppUser blockedUntil(DateTime blockedUntil) {
    
    this.blockedUntil = blockedUntil;
    return this;
  }

   /**
   * Get blockedUntil
   * @return blockedUntil
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getBlockedUntil() {
    return blockedUntil;
  }


  public void setBlockedUntil(DateTime blockedUntil) {
    this.blockedUntil = blockedUntil;
  }


  public StoryAppUser blockedAt(DateTime blockedAt) {
    
    this.blockedAt = blockedAt;
    return this;
  }

   /**
   * Get blockedAt
   * @return blockedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getBlockedAt() {
    return blockedAt;
  }


  public void setBlockedAt(DateTime blockedAt) {
    this.blockedAt = blockedAt;
  }


  public StoryAppUser blockedBy(String blockedBy) {
    
    this.blockedBy = blockedBy;
    return this;
  }

   /**
   * Get blockedBy
   * @return blockedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBlockedBy() {
    return blockedBy;
  }


  public void setBlockedBy(String blockedBy) {
    this.blockedBy = blockedBy;
  }


  public StoryAppUser createdAt(DateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(DateTime createdAt) {
    this.createdAt = createdAt;
  }


  public StoryAppUser createdBy(String createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }


  public StoryAppUser modifiedAt(DateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(DateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public StoryAppUser modifiedBy(String modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(String modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public StoryAppUser id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoryAppUser storyAppUser = (StoryAppUser) o;
    return Objects.equals(this.appId, storyAppUser.appId) &&
        Objects.equals(this.userId, storyAppUser.userId) &&
        Objects.equals(this.blockDescription, storyAppUser.blockDescription) &&
        Objects.equals(this.blocked, storyAppUser.blocked) &&
        Objects.equals(this.blockedUntil, storyAppUser.blockedUntil) &&
        Objects.equals(this.blockedAt, storyAppUser.blockedAt) &&
        Objects.equals(this.blockedBy, storyAppUser.blockedBy) &&
        Objects.equals(this.createdAt, storyAppUser.createdAt) &&
        Objects.equals(this.createdBy, storyAppUser.createdBy) &&
        Objects.equals(this.modifiedAt, storyAppUser.modifiedAt) &&
        Objects.equals(this.modifiedBy, storyAppUser.modifiedBy) &&
        Objects.equals(this.id, storyAppUser.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(appId, userId, blockDescription, blocked, blockedUntil, blockedAt, blockedBy, createdAt, createdBy, modifiedAt, modifiedBy, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoryAppUser {\n");
    sb.append("    appId: ").append(toIndentedString(appId)).append("\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    blockDescription: ").append(toIndentedString(blockDescription)).append("\n");
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    blockedUntil: ").append(toIndentedString(blockedUntil)).append("\n");
    sb.append("    blockedAt: ").append(toIndentedString(blockedAt)).append("\n");
    sb.append("    blockedBy: ").append(toIndentedString(blockedBy)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

