/*
 * Id service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: support@breffi.ru
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.breffi.storyid.generated_api.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.joda.time.DateTime;

/**
 * StoryDemographicsDTO
 */

public class StoryDemographicsDTO {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_SURNAME = "surname";
  @SerializedName(SERIALIZED_NAME_SURNAME)
  private String surname;

  public static final String SERIALIZED_NAME_PATRONYMIC = "patronymic";
  @SerializedName(SERIALIZED_NAME_PATRONYMIC)
  private String patronymic;

  public static final String SERIALIZED_NAME_GENDER = "gender";
  @SerializedName(SERIALIZED_NAME_GENDER)
  private Boolean gender;

  public static final String SERIALIZED_NAME_BIRTHDAY = "birthday";
  @SerializedName(SERIALIZED_NAME_BIRTHDAY)
  private DateTime birthday;


  public StoryDemographicsDTO name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public StoryDemographicsDTO surname(String surname) {
    
    this.surname = surname;
    return this;
  }

   /**
   * Get surname
   * @return surname
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getSurname() {
    return surname;
  }


  public void setSurname(String surname) {
    this.surname = surname;
  }


  public StoryDemographicsDTO patronymic(String patronymic) {
    
    this.patronymic = patronymic;
    return this;
  }

   /**
   * Get patronymic
   * @return patronymic
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPatronymic() {
    return patronymic;
  }


  public void setPatronymic(String patronymic) {
    this.patronymic = patronymic;
  }


  public StoryDemographicsDTO gender(Boolean gender) {
    
    this.gender = gender;
    return this;
  }

   /**
   * Get gender
   * @return gender
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getGender() {
    return gender;
  }


  public void setGender(Boolean gender) {
    this.gender = gender;
  }


  public StoryDemographicsDTO birthday(DateTime birthday) {
    
    this.birthday = birthday;
    return this;
  }

   /**
   * Get birthday
   * @return birthday
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DateTime getBirthday() {
    return birthday;
  }


  public void setBirthday(DateTime birthday) {
    this.birthday = birthday;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StoryDemographicsDTO storyDemographicsDTO = (StoryDemographicsDTO) o;
    return Objects.equals(this.name, storyDemographicsDTO.name) &&
        Objects.equals(this.surname, storyDemographicsDTO.surname) &&
        Objects.equals(this.patronymic, storyDemographicsDTO.patronymic) &&
        Objects.equals(this.gender, storyDemographicsDTO.gender) &&
        Objects.equals(this.birthday, storyDemographicsDTO.birthday);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, surname, patronymic, gender, birthday);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StoryDemographicsDTO {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    surname: ").append(toIndentedString(surname)).append("\n");
    sb.append("    patronymic: ").append(toIndentedString(patronymic)).append("\n");
    sb.append("    gender: ").append(toIndentedString(gender)).append("\n");
    sb.append("    birthday: ").append(toIndentedString(birthday)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

